# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b05f2c91c9d90f8d1e5c637b38fa7dc24b5fc3773e6bf1b2d21a712a674938e8e257a44381b9aafb90455cd9ce0c647403607c5cd3bd1539d7862b41b3638466

test:
  secret_key_base: 617a39fc10f28733367b0a9f7bf9241124c41571cf1c77b1fac1a85ae3908288f007448e1e9d8bef17a50d07e89841c3f2658126e0a3b44e08d79a738df775a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
